# Generated by Django 5.0.3 on 2024-03-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                default="Images/None/sampleImg.jpg", upload_to="Images"
            ),
        ),
    ]
